Repository sandeepraina-dsd19/FoodOrderingApp-Frontend, pull requests merged in 2021-06, with the labels that each got.

#2 Adding HomeJs part II feature & updating readme
  AfterAddingHomeScreenXhr.jpg
  AfterHeaderJs.jpg
  README.md
  src/screens/home/Home.js
Labels: documentation, enhancement

#3 Checkout page added and some issue resolved
  package-lock.json
  package.json
  src/FoodOrdering.js
  src/common/customizedsnackbar/CustomizedSnackBar.js
  src/common/orderitems/OrderItems.css
  src/common/orderitems/OrderItems.js
  src/index.js
  src/screens/checkout/Checkout.css
  src/screens/checkout/Checkout.js
  src/screens/details/Details.css
  src/screens/details/Details.js
  src/screens/home/Home.js
Labels: enhancement

#5 Update Checkout.js
  src/screens/checkout/Checkout.js
Labels: bug

#6 Adding dynamic Profile details & Documentation
  README.md
  checkout.jpg
  details.jpg
  login.jpg
  order.jpg
  signup.jpg
  src/screens/profile/Profile.js
Labels: documentation, enhancement
